### ISSUE TITLE
More detail on README Usage

### ISSUE THREAD

**Issue by robbpaulsen** [sensepost/hash-cracker#28]
Hi,

So I just clone the repo, great work on the automatic optimezed options, I never figured out myself how to turn off hardware monitor. I just have some trouble using the switches/flags or maybe I missunderstood what the script does. It gave me the impression of being like a modular framework to have everything related to hashcat/wordlists/rules/processors/Pack/etc in one place and inside a framework, but when I execute the main script besides the initial setup I can't figure out how to use main script to specify Mode, Attack type, wordlist or mask with switches/flags. 

I do have CWeL installed and Python2, aspell, pyenchant, etc, there are no issues on the requirements side or drivers.

**Comment by crypt0rr** [comment]
Hola!

By default [flags](https://github.com/sensepost/hash-cracker#flags) are optional. When running [hash-cracker.sh](https://github.com/sensepost/hash-cracker#usage) you are presented with currently ([v3.6](https://github.com/sensepost/hash-cracker/releases/tag/v3.6)) 20 options. If you want more information about the options themselfs, please run `./hash-cracker.sh --module-info`.

All options have their own workings and requirements, when you for example chose option 1, you will be asked to enter the hashtype (e.g. 1000 for NTLM), the path to your hashlist. After you hit enter the job will start running.

If you have further questions please reopen this issue.

**Comment by robbpaulsen** [comment]
Thanks,

Let me try it like that, by the way do u speak spanish ? I'm mexican if u speak spanish It would be some what easier to explain certain things, thaks again, I'll get back tou you once I tried what you told me.

**Comment by crypt0rr** [comment]
> Thanks,
> 
> Let me try it like that, by the way do u speak spanish ? I'm mexican if u speak spanish It would be some what easier to explain certain things, thaks again, I'll get back tou you once I tried what you told me.

Nope, unfortunatly not. Otherwise contact me on Discord. Good luck!

**Comment by robbpaulsen** [comment]
I know the thread is closed but just wanted to tell you , you are a hell of a passwd crackr, you really did actually automated all the basic stuff and step it full to advanced approaches, I honestly want to know 2 thing:

- How long took you to actually dig more on all the advanced subjects?, its been very slow for me from certain point and in the pentesting community this is not even close to be lightly approached as a subject

- And lastly are you ever gonna add something more or are you currently working on something else?

**Comment by crypt0rr** [comment]
Good to hear you like it! 

1. It took me about a year of testing in multiple environments to find sweet spots for the specific options that are currently in hash-cracker. Doesn't mean that things can't be improved tho. It can be helpfull to give these blogsposts a read: https://sensepost.com/blog/cracking/
2. There is a small wishlist, but I don't have a timeline currently because of time. For example:
    - Use of a configuration file which is easiliy open to the user to set static values, e.g. the path of hashcat
    - Parameter handling when starting `./hash-cracker.sh` - ability to specifiy directly which hashtype / mode you want to run instead of going through the menu for each job you wan tot run on the same dataset.

**Comment by crypt0rr** [comment]
@robbpaulsen Fresh release: https://github.com/sensepost/hash-cracker/releases/tag/v3.7

**Comment by robbpaulsen** [comment]
Thanks a lot, for the update, I'll check it out ASAP, and I'll also deep read the blog posts, thanks a lot for sharing, have a nice day bro
