### ISSUE TITLE
Statis Wordlist Directory #ComplementConfFeature

### ISSUE THREAD

**Issue by robbpaulsen** [sensepost/hash-cracker#30]
Hey what up, I passed the whole night with the script, I liked the new conf feature, could you  explain what file to mod to add a static directory for the Wordlists/Dcitonaries also? , I've worked very long with a directory layout for less typing.

If you could just point me in the right direction I can manage dont worry, I just dont want to touch the worng thing, I had to rm and reinstall the hashcatutils and pyenchant, dont want o go over that again, that issue was my fault btw, thanks again, and have a nice day.

**Comment by crypt0rr** [comment]
Good to hear! I will certainly have a look at this for a future release. For now, it is not nice, but at least it works.

Edit the `scripts/selectors/wordlist.sh`. You can have as follows:

`#!/bin/bash
# Author: crypt0rr - https://github.com/crypt0rr/
RESTART="source scripts/selectors/wordlist.sh"

# read -e -p "Enter full path to wordlist: " WORDLIST
# if [ -f "$WORDLIST" ]; then
#     echo "Wordlist" $WORDLIST "selected."
# else
#     echo "File does not exist, try again."; $RESTART
# fi
WORDLIST=wordlists/ignis-1K.txt`

Where `WORDLIST=` can either be a specific wordlist or a folder containing multiple wordlists.

**Comment by robbpaulsen** [comment]
Thanks a lot, bro, have a nice day.

**Comment by crypt0rr** [comment]
@robbpaulsen If you want to have a look at a preview with static wordlist configuration, please do the following.

```
git pull
git checkout v3.8
```

Don't forget to switch back to `master` (`git checkout master`) when v3.8 is released.
