### ISSUE TITLE
Custom hashlist with a extension is seen as a hash.

### ISSUE THREAD

**Issue by justin-p** [sensepost/hash-cracker#35]
When using a custom hashlist name with an extension, without setting a full path, hashcat picks up the file as a hash.

```
$ ./hash-cracker.sh --static

[...SNIP...]

Hash 'input.txt': Token length exception

* Token length exception: 1/1 hashes
  This error happens if the wrong hash type is specified, if the hashes are
  malformed, or if input is otherwise not as expected (for example, if the
  --username option is used but no username is present)

No hashes loaded.
```

**Comment by crypt0rr** [comment]
Is this issue occuring when running a specific job? I tried recreating this with option 1 and 6 but was not successful.

`$ ./hash-cracker.sh --static
hash-cracker v4.0 by crypt0rr (https://github.com/crypt0rr)
                                           
Mandatory modules:                         
[+] Hashcat is executable                  
[+] Potfile hash-cracker.pot present       
                                           
Optional modules:                          
[+] common-substr-linux is executable      
[+] Python2 is executable                  
[+] Expander is executable                 
[+] CeWL is executable                     
                                           
Variable Parameters:                       
[+] Optimised kernels enabled              
[+] Loopback enabled                       
[-] Hardware monitoring disabled           
                                           
Static parameters:                         
[+] Potfile: hash-cracker.pot              
[+] Hashlist: input.txt                    
[+] Hashtype: 1000                         
[+] Wordlist 1: hashmob.net_2023-11-05.found
[+] Wordlist 2: wordlists/ignis-10M.txt    
                                           
[...]             
                                           
Please enter job number or type exit: 6    
Single or Multiple wordlist mode? S/M: m   
Enter path to directory containing multiple wordlists: wordlists/ignis-1M.txt
Directory wordlists/ignis-1M.txt selected. 
hashcat (v6.2.6-418-g19e20c7d0) starting

Session..........: hashcat
Status...........: Running                 
Hash.Mode........: 1000 (NTLM)             
Hash.Target......: input.txt               
Time.Started.....: Fri Nov 10 15:27:08 2023 (1 sec)
Time.Estimated...: Fri Nov 10 15:27:12 2023 (3 secs)
[...]   `

**Comment by justin-p** [comment]
Might have been a remnant of local changes when we tested the 4.0.0 branch. Pulled a clean version, issue no longer exists.
